# Application config
spring.application.name=backend-hospital
server.port=9092

# Database (application-db) config
spring.datasource.url=jdbc:postgresql://26.62.34.191:5435/application
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Redis config
spring.data.redis.host=redis-cache
spring.data.redis.port=6379

# Keycloak config
keycloak.realm=hospital-realm
keycloak.auth-server-url=http://26.62.34.191:9091
keycloak.resource=hospital-client-keycloak-be
keycloak.credentials.secret=UeNrGL4zvTBoBszFQ5iP6NFaz6Rp2dyn
keycloak.public-client=false
keycloak.admin-username=administrator
keycloak.admin-password=administrator
#keycloak.security-constraints[0].authRoles[0]=USER
#keycloak.security-constraints[0].securityCollections[0].patterns[0]=/*

# Security Configuration
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://26.62.34.191:9091/realms/hospital-realm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://26.62.34.191:9091/realms/hospital-realm/protocol/openid-connect/certs

# JWT Configuration
jwt.auth.converter.resource-id=hospital
jwt.auth.converter.principal-attribute=preferred_username
jwt.secret=/I2!J&|iq+?vDG:
jwt.expiration=3600000

# Cloudinary Configuration
cloudinary.cloud-name=dhpke1vua
cloudinary.api-key=397636321945872
cloudinary.api-secret=41AdZS_9a4If71dXEYZ-q5G4uXw
cloudinary.secure=true

# Logging Configuration
logging.level.org.springframework.security=INFO

# Momo Configuration
momo.partner-code = MOMOXXXX2020
momo.access-key: your-access-key
momo.secret-key: your-secret-key
momo.endpoint: https://test-payment.momo.vn/v2/gateway/api/create
momo.redirect-url: https://your-frontend/payment-result
momo.ipn-url: https://your-backend/api/v1/app/payment/momo/callback
